version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
  mongodb:
    image: mongo
    ports:
      - 27017:27017
