name: Backend Actions

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      PORT: ${{ secrets.PORT }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Start backend server
        working-directory: backend
        run: npm start &
